"""empty message

Revision ID: cd09a8b7a74e
Revises: 83c8a27837dd
Create Date: 2026-01-18 10:25:43.709382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd09a8b7a74e'
down_revision = '83c8a27837dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.drop_column('given_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('given_id', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
