"""empty message

Revision ID: f6a34e8dae65
Revises: 42e98b3c835b
Create Date: 2026-01-17 21:52:22.582352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a34e8dae65'
down_revision = '42e98b3c835b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('given_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option_leg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('position_type', sa.String(), nullable=False),
    sa.Column('strike', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option_leg')
    op.drop_table('strategy')
    # ### end Alembic commands ###
